disabled_rules: # rule identifiers turned on by default to exclude from running
  - nesting
  - switch_case_alignment

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .swiftpm

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
